name: docker login
on:
    workflow_dispatch:
    push:
       branches:
            - main
jobs:
    docker:
        name: containerization
        permissions:
            contents: write
            packages: write
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v5

            - name: docker login
              uses: docker/login-action@v3.5.0
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: GHCR login
              uses: docker/login-action@v3.5.0
              with:
                registry: ghcr.io
                username: ${{github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}
    